-- truncate table book;
drop table if exists book CASCADE;
create table book
(
    id     bigint generated by default as identity,
    author varchar(20) not null,
    title  varchar(50) not null,
    primary key (id)
);